
CREATE OR REPLACE TRIGGER SINIF_NOT_ID_GEN
BEFORE INSERT ON SINIF_NOT
FOR EACH ROW --her bir insert için tek tek çalışıyor (toplu insert olması ihtimali)
DECLARE 
	new_id NUMBER;
BEGIN 
	get_next_id('SINIF_NOT', 'SINIF_NOT_ID', new_id);
	
	:NEW.SINIF_NOT_ID := new_id;
	:NEW.TARIH := SYSDATE;
END;
/



CREATE OR REPLACE TRIGGER ILETISIM_ID_GEN
BEFORE INSERT ON ILETISIM
FOR EACH ROW
DECLARE
  new_id NUMBER;
BEGIN
  get_next_id('ILETISIM', 'ILETISIM_ID', new_id);
  :NEW.ILETISIM_ID := new_id;
END;
/


CREATE OR REPLACE TRIGGER KISI_ID_GEN
BEFORE INSERT ON KISI
FOR EACH ROW
DECLARE
  new_id NUMBER;
BEGIN
  get_next_id('KISI', 'KISI_ID', new_id);
  :NEW.KISI_ID := new_id;
END;
/

CREATE OR REPLACE TRIGGER OGRENCI_ID_GEN
BEFORE INSERT ON OGRENCI
FOR EACH ROW
DECLARE
  new_id NUMBER;
BEGIN
  get_next_id('OGRENCI', 'OGRENCI_ID', new_id);
  :NEW.OGRENCI_ID := new_id;
END;
/

CREATE OR REPLACE TRIGGER DERS_ID_GEN
BEFORE INSERT ON DERS
FOR EACH ROW
DECLARE
  new_id NUMBER;
BEGIN
  get_next_id('DERS', 'DERS_ID', new_id);
  :NEW.DERS_ID := new_id;
END;
/


CREATE OR REPLACE TRIGGER CINSIYET_ID_GEN
BEFORE INSERT ON CINSIYET
FOR EACH ROW
BEGIN	
  :NEW.DERS_ID := SEQ_GENEL.next_val;
END;
/
