CREATE OR REPLACE VIEW V_SINIF_SONUC AS
SELECT
	s.SINIF_ID,
	d.DERS_ADI,
	k.AD,
	k.SOYAD,
	toplam_grade(s.SINIF_ID, o.OGRENCI_ID) AS AGIRLIKLI_NOT_ORTALAMASI,
	harf_notu(s.SINIF_ID, toplam_grade(s.SINIF_ID, o.OGRENCI_ID)) AS harf_notu
FROM
	SINIF s
	JOIN DERS d ON s.DERS_ID = d.DERS_ID
	JOIN SINIF_OGRENCI so ON s.SINIF_ID = so.SINIF_ID
	JOIN OGRENCI o ON so.OGRENCI_ID = O.OGRENCI_ID
	JOIN KISI k ON k.KISI_ID = o.KISI_ID;


CREATE OR REPLACE VIEW V_SINIF_DURUM AS
SELECT
  s.SINIF_ID,
  d.DERS_ADI,

  (
    SELECT hs.ALT_SINIR
    FROM HARF_SKALASI hs
    WHERE hs.SINIF_ID = s.SINIF_ID AND hs.HARF_SIMGE = 'D'
  ) AS GECME_NOTU,

  ogrenci_sayac(s.SINIF_ID) AS OGRENCI_SAYISI,

  sinif_ortalama(s.SINIF_ID) AS SINIF_ORTALAMASI,

  kalan_ogrenci_sayac(s.SINIF_ID) AS KALAN_OGRENCI,

  ogrenci_sayac(s.SINIF_ID) - kalan_ogrenci_sayac(s.SINIF_ID) AS GECEN_OGRENCI,

  basari_orani(s.SINIF_ID) AS BASARI_ORANI

FROM
  SINIF s
  JOIN DERS d ON s.DERS_ID = d.DERS_ID;


